const CASHBOOK_ENTRY_TYPE = {
  PAYMENT: "payment",
  RECEIPT: "receipt",
  DEPOSIT: "deposit",
  JOURNAL: "journal",
};

const CASHBOOK_DIRECTION = {
  INFLOW: "inflow",
  OUTFLOW: "outflow",
};

const CASHBOOK_ENTRY_TYPE_VALUES = Object.values(CASHBOOK_ENTRY_TYPE);
const CASHBOOK_DIRECTION_VALUES = Object.values(CASHBOOK_DIRECTION);

const CASHBOOK_EXPORT_MAX_ROWS = Math.max(
  1,
  Number(process.env.CASHBOOK_EXPORT_MAX_ROWS) || 10000
);

const LEGACY_CASHBOOK_MAX_ROWS = Math.max(
  1,
  Number(process.env.LEGACY_CASHBOOK_MAX_ROWS) || 1000
);

module.exports = {
  CASHBOOK_ENTRY_TYPE,
  CASHBOOK_DIRECTION,
  CASHBOOK_ENTRY_TYPE_VALUES,
  CASHBOOK_DIRECTION_VALUES,
  CASHBOOK_EXPORT_MAX_ROWS,
  LEGACY_CASHBOOK_MAX_ROWS,
};
