const EXPENSE_REQUEST_STATUS = {
  DRAFT: "draft",
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  PAID: "paid",
};

const COMMITTED_STATUSES = [
  EXPENSE_REQUEST_STATUS.PENDING,
  EXPENSE_REQUEST_STATUS.APPROVED,
  EXPENSE_REQUEST_STATUS.PAID,
];

const EDITABLE_EXPENSE_STATUSES = [
  EXPENSE_REQUEST_STATUS.DRAFT,
  EXPENSE_REQUEST_STATUS.REJECTED,
];

const SUBMITTABLE_EXPENSE_STATUSES = [
  EXPENSE_REQUEST_STATUS.DRAFT,
  EXPENSE_REQUEST_STATUS.REJECTED,
];

const EXPENSE_REQUEST_STATUS_VALUES = Object.values(EXPENSE_REQUEST_STATUS);

module.exports = {
  EXPENSE_REQUEST_STATUS,
  COMMITTED_STATUSES,
  EDITABLE_EXPENSE_STATUSES,
  SUBMITTABLE_EXPENSE_STATUSES,
  EXPENSE_REQUEST_STATUS_VALUES,
};
