-- RBAC: Seed permission catalog from docs/PERMISSION_CATALOG.md (§24 deduped index)
-- Idempotent: ON CONFLICT (permission_key) DO NOTHING
-- Does not seed role_permissions or administrative_charge_permissions

INSERT INTO permissions (permission_key, category, resource, action, data_scope, description, is_active)
VALUES
    ('dashboard.summary.read', 'Academics', 'summary', 'read', 'SCHOOL', 'View school dashboard totals (students, teachers, classes, attendance %)', true),
    ('dashboard.finance.read', 'Finance', 'finance', 'read', 'SCHOOL', 'View finance dashboard widgets (allocations, spend, balances)', true),
    ('dashboard.staff_post.read', 'Teacher', 'staff_post', 'read', 'SCHOOL', 'View staff-post vacancy and strength widgets', true),
    ('dashboard.activity.read', 'Finance', 'activity', 'read', 'SCHOOL', 'View activity pipeline dashboard', true),
    ('dashboard.stock.read', 'Finance', 'stock', 'read', 'SCHOOL', 'View stock register summary dashboard', true),
    ('student.read', 'Student', 'student', 'read', 'SCHOOL', 'List and view student records', true),
    ('student.create', 'Student', 'student', 'create', 'SCHOOL', 'Add a single student record', true),
    ('student.update', 'Student', 'student', 'update', 'SCHOOL', 'Edit student demographics and enrollment fields', true),
    ('student.delete', 'Student', 'student', 'delete', 'SCHOOL', 'Soft-delete or deactivate a student', true),
    ('student.import.execute', 'Student', 'import', 'execute', 'SCHOOL', 'Bulk import students from spreadsheet upload', true),
    ('student.import.template', 'Student', 'import', 'template', 'SCHOOL', 'Download student import template', true),
    ('student.export.execute', 'Student', 'export', 'execute', 'SCHOOL', 'Export student roster to file', true),
    ('student.promotion.execute', 'Student', 'promotion', 'execute', 'SCHOOL', 'Run promotion workflow for a student', true),
    ('class.read', 'Academics', 'class', 'read', 'SCHOOL', 'List class definitions', true),
    ('class.create', 'Academics', 'class', 'create', 'SCHOOL', 'Create a class definition', true),
    ('section.read', 'Academics', 'section', 'read', 'SCHOOL', 'List section definitions', true),
    ('section.create', 'Academics', 'section', 'create', 'SCHOOL', 'Create a section definition', true),
    ('class_section.read', 'Academics', 'class_section', 'read', 'SCHOOL', 'List class-section combinations', true),
    ('class_section.create', 'Academics', 'class_section', 'create', 'SCHOOL', 'Create a class-section combination', true),
    ('class_section.update', 'Academics', 'class_section', 'update', 'SCHOOL', 'Update a class-section combination', true),
    ('class_section.delete', 'Academics', 'class_section', 'delete', 'SCHOOL', 'Remove a class-section combination', true),
    ('subject.read', 'Academics', 'subject', 'read', 'SCHOOL', 'List subjects and applicable classes', true),
    ('subject.create', 'Academics', 'subject', 'create', 'SCHOOL', 'Create a subject', true),
    ('subject.update', 'Academics', 'subject', 'update', 'SCHOOL', 'Update subject name, code, or applicable classes', true),
    ('subject.delete', 'Academics', 'subject', 'delete', 'SCHOOL', 'Delete a subject', true),
    ('attendance.read', 'Attendance', 'attendance', 'read', 'ASSIGNED_CLASS', 'View attendance registers and daily summaries', true),
    ('attendance.student.read', 'Attendance', 'student', 'read', 'SCHOOL', 'View attendance history for a specific student', true),
    ('attendance.mark', 'Attendance', 'attendance', 'mark', 'ASSIGNED_CLASS', 'Mark attendance for a class/period', true),
    ('attendance.update', 'Attendance', 'attendance', 'update', 'ASSIGNED_CLASS', 'Correct previously marked attendance', true),
    ('exam.read', 'Academics', 'exam', 'read', 'SCHOOL', 'List examinations', true),
    ('exam.create', 'Academics', 'exam', 'create', 'SCHOOL', 'Create an examination definition', true),
    ('mark.read', 'Academics', 'mark', 'read', 'ASSIGNED_CLASS', 'View marks entries for assigned classes/subjects', true),
    ('mark.create', 'Academics', 'mark', 'create', 'ASSIGNED_CLASS', 'Enter marks for students', true),
    ('result.read', 'Academics', 'result', 'read', 'ASSIGNED_CLASS', 'View computed student results', true),
    ('result.create', 'Academics', 'result', 'create', 'ASSIGNED_CLASS', 'Record or publish student result rows', true),
    ('report_card.read', 'Academics', 'report_card', 'read', 'ASSIGNED_CLASS', 'Generate or view a student report card', true),
    ('timetable.read', 'Timetable', 'timetable', 'read', 'SCHOOL', 'View school timetables', true),
    ('timetable.read_by_class', 'Timetable', 'timetable', 'read_by_class', 'SCHOOL', 'View timetable for a specific class-section', true),
    ('timetable.create', 'Timetable', 'timetable', 'create', 'SCHOOL', 'Create timetable periods', true),
    ('timetable.delete', 'Timetable', 'timetable', 'delete', 'SCHOOL', 'Remove timetable periods', true),
    ('teacher.read', 'Teacher', 'teacher', 'read', 'SCHOOL', 'List and view teacher profiles', true),
    ('teacher.create', 'Teacher', 'teacher', 'create', 'SCHOOL', 'Onboard a new teacher record', true),
    ('teacher.update', 'Teacher', 'teacher', 'update', 'SCHOOL', 'Edit teacher profile and employment fields', true),
    ('teacher.delete', 'Teacher', 'teacher', 'delete', 'SCHOOL', 'Remove or deactivate a teacher record', true),
    ('teacher_subject_assignment.read', 'Teacher', 'teacher_subject_assignment', 'read', 'SCHOOL', 'View all teacher-subject-class assignments', true),
    ('teacher_subject_assignment.read_own', 'Teacher', 'teacher_subject_assignment', 'read_own', 'SELF', 'View own subject assignments', true),
    ('teacher_subject_assignment.assign', 'Teacher', 'teacher_subject_assignment', 'assign', 'SCHOOL', 'Assign a teacher to subject/class', true),
    ('teacher_subject_assignment.relieve', 'Teacher', 'teacher_subject_assignment', 'relieve', 'SCHOOL', 'End an active subject assignment', true),
    ('staff_post.read', 'Teacher', 'staff_post', 'read', 'SCHOOL', 'View staff post catalog and vacancy counts', true),
    ('staff_post.create', 'Teacher', 'staff_post', 'create', 'SCHOOL', 'Create a staff post definition', true),
    ('staff_post.update', 'Teacher', 'staff_post', 'update', 'SCHOOL', 'Update staff post details or sanctioned count', true),
    ('staff_post.delete', 'Teacher', 'staff_post', 'delete', 'SCHOOL', 'Deactivate or remove a staff post', true),
    ('staff_post_assignment.read', 'Teacher', 'staff_post_assignment', 'read', 'SCHOOL', 'View teacher-staff-post assignments', true),
    ('staff_post_assignment.read_vacant', 'Teacher', 'staff_post_assignment', 'read_vacant', 'SCHOOL', 'View vacant staff posts', true),
    ('staff_post_assignment.assign', 'Teacher', 'staff_post_assignment', 'assign', 'SCHOOL', 'Assign a teacher to a staff post', true),
    ('staff_post_assignment.relieve', 'Teacher', 'staff_post_assignment', 'relieve', 'SCHOOL', 'Relieve a teacher from a staff post', true),
    ('staff_service_history.read', 'Teacher', 'staff_service_history', 'read', 'SCHOOL', 'View staff service history events', true),
    ('staff_service_history.service_book.read', 'Teacher', 'service_book', 'read', 'SCHOOL', 'View teacher service book', true),
    ('staff_service_history.transfer.read', 'Teacher', 'transfer', 'read', 'SCHOOL', 'View transfer history', true),
    ('staff_service_history.designation.read', 'Teacher', 'designation', 'read', 'SCHOOL', 'View designation history', true),
    ('staff_service_history.tenure.read', 'Teacher', 'tenure', 'read', 'SCHOOL', 'View tenure summary', true),
    ('administration.charge.read', 'Administration', 'charge', 'read', 'SCHOOL', 'View school administrative charge catalog', true),
    ('administration.charge.read_details', 'Administration', 'charge', 'read_details', 'SCHOOL', 'View charge detail panel (assignments, holders)', true),
    ('administration.charge.create', 'Administration', 'charge', 'create', 'SCHOOL', 'Add a charge type to the school catalog', true),
    ('administration.charge.update', 'Administration', 'charge', 'update', 'SCHOOL', 'Edit charge name or description', true),
    ('administration.charge.activate', 'Administration', 'charge', 'activate', 'SCHOOL', 'Activate or deactivate a charge type', true),
    ('administration.charge_assignment.read', 'Administration', 'charge_assignment', 'read', 'SCHOOL', 'View teacher charge assignments', true),
    ('administration.charge_assignment.assign', 'Administration', 'charge_assignment', 'assign', 'SCHOOL', 'Assign a charge to a teacher', true),
    ('administration.charge_assignment.update', 'Administration', 'charge_assignment', 'update', 'SCHOOL', 'Update an active assignment', true),
    ('administration.charge_assignment.relieve', 'Administration', 'charge_assignment', 'relieve', 'SCHOOL', 'Relieve a teacher from a charge', true),
    ('finance.financial_year.read', 'Finance', 'financial_year', 'read', 'SCHOOL', 'List and view financial years', true),
    ('finance.financial_year.create', 'Finance', 'financial_year', 'create', 'SCHOOL', 'Create a financial year for a school', true),
    ('finance.financial_year.update', 'Finance', 'financial_year', 'update', 'SCHOOL', 'Edit financial year dates or remarks', true),
    ('finance.financial_year.activate', 'Finance', 'financial_year', 'activate', 'SCHOOL', 'Set a financial year as active', true),
    ('finance.financial_year.close', 'Finance', 'financial_year', 'close', 'SCHOOL', 'Close a financial year', true),
    ('finance.financial_year.delete', 'Finance', 'financial_year', 'delete', 'SYSTEM', 'Hard-delete a financial year (bootstrap / correction)', true),
    ('finance.budget_head.read', 'Finance', 'budget_head', 'read', 'SYSTEM', 'View budget heads (parent heads)', true),
    ('finance.budget_head.create', 'Finance', 'budget_head', 'create', 'SYSTEM', 'Create a budget head', true),
    ('finance.budget_head.update', 'Finance', 'budget_head', 'update', 'SYSTEM', 'Update a budget head', true),
    ('finance.budget_head.activate', 'Finance', 'budget_head', 'activate', 'SYSTEM', 'Activate or deactivate a budget head', true),
    ('finance.budget_sub_head.read', 'Finance', 'budget_sub_head', 'read', 'SYSTEM', 'View budget sub-heads', true),
    ('finance.budget_sub_head.create', 'Finance', 'budget_sub_head', 'create', 'SYSTEM', 'Create a budget sub-head under a head', true),
    ('finance.budget_sub_head.update', 'Finance', 'budget_sub_head', 'update', 'SYSTEM', 'Update a budget sub-head', true),
    ('finance.budget_sub_head.activate', 'Finance', 'budget_sub_head', 'activate', 'SYSTEM', 'Activate or deactivate a budget sub-head', true),
    ('finance.budget_allocation.read', 'Finance', 'budget_allocation', 'read', 'SCHOOL', 'View budget allocations for a school/FY', true),
    ('finance.budget_allocation.read_summary', 'Finance', 'budget_allocation', 'read_summary', 'SCHOOL', 'View allocation summary aggregates', true),
    ('finance.budget_allocation.read_balance', 'Finance', 'budget_allocation', 'read_balance', 'SCHOOL', 'View remaining balance for an allocation', true),
    ('finance.budget_allocation.create', 'Finance', 'budget_allocation', 'create', 'SCHOOL', 'Create a budget allocation', true),
    ('finance.budget_allocation.update', 'Finance', 'budget_allocation', 'update', 'SCHOOL', 'Update allocation amount or responsible teacher', true),
    ('finance.budget_allocation.activate', 'Finance', 'budget_allocation', 'activate', 'SCHOOL', 'Activate or deactivate an allocation', true),
    ('finance.activity.read', 'Finance', 'activity', 'read', 'SCHOOL', 'List and view school activities', true),
    ('finance.activity.read_dashboard', 'Finance', 'activity', 'read_dashboard', 'SCHOOL', 'View activity dashboard metrics', true),
    ('finance.activity.read_timeline', 'Finance', 'activity', 'read_timeline', 'SCHOOL', 'View activity audit timeline', true),
    ('finance.activity.create', 'Finance', 'activity', 'create', 'SELF', 'Create an activity proposal', true),
    ('finance.activity.update', 'Finance', 'activity', 'update', 'SELF', 'Edit draft activity details', true),
    ('finance.activity.submit', 'Finance', 'activity', 'submit', 'SELF', 'Submit activity for approval', true),
    ('finance.activity.approve', 'Finance', 'activity', 'approve', 'SCHOOL', 'Approve a submitted activity', true),
    ('finance.activity.reject', 'Finance', 'activity', 'reject', 'SCHOOL', 'Reject a submitted activity', true),
    ('finance.activity.complete', 'Finance', 'activity', 'complete', 'SELF', 'Mark activity completed', true),
    ('finance.activity.update_status', 'Finance', 'activity', 'update_status', 'SCHOOL', 'Override activity status (admin correction)', true),
    ('finance.activity.upload', 'Finance', 'activity', 'upload', 'SELF', 'Upload activity supporting document', true),
    ('finance.expense_request.read', 'Finance', 'expense_request', 'read', 'SCHOOL', 'List and view expense requests', true),
    ('finance.expense_request.read_summary', 'Finance', 'expense_request', 'read_summary', 'SCHOOL', 'View expense request summary stats', true),
    ('finance.expense_request.create', 'Finance', 'expense_request', 'create', 'SELF', 'Create a draft expense request', true),
    ('finance.expense_request.update', 'Finance', 'expense_request', 'update', 'SELF', 'Edit a draft expense request', true),
    ('finance.expense_request.delete', 'Finance', 'expense_request', 'delete', 'SELF', 'Delete a draft expense request', true),
    ('finance.expense_request.submit', 'Finance', 'expense_request', 'submit', 'SELF', 'Submit expense request for approval', true),
    ('finance.expense_request.approve', 'Finance', 'expense_request', 'approve', 'SCHOOL', 'Approve a pending expense request', true),
    ('finance.expense_request.reject', 'Finance', 'expense_request', 'reject', 'SCHOOL', 'Reject a pending expense request', true),
    ('finance.expense_request.mark_paid', 'Finance', 'expense_request', 'mark_paid', 'SCHOOL', 'Record payment / mark expense as paid', true),
    ('finance.quotation.read', 'Finance', 'quotation', 'read', 'SCHOOL', 'List and view quotations', true),
    ('finance.quotation.read_config', 'Finance', 'quotation', 'read_config', 'SCHOOL', 'View quotation configuration thresholds', true),
    ('finance.quotation.read_comparison', 'Finance', 'quotation', 'read_comparison', 'SCHOOL', 'Compare quotations for an expense request', true),
    ('finance.quotation.create', 'Finance', 'quotation', 'create', 'SELF', 'Submit a vendor quotation', true),
    ('finance.quotation.select', 'Finance', 'quotation', 'select', 'SCHOOL', 'Select winning quotation for an expense request', true),
    ('finance.cashbook.read', 'Finance', 'cashbook', 'read', 'SCHOOL', 'View finance cashbook entries', true),
    ('finance.cashbook.read_summary', 'Finance', 'cashbook', 'read_summary', 'SCHOOL', 'View cashbook summary totals', true),
    ('finance.cashbook.export', 'Finance', 'cashbook', 'export', 'SCHOOL', 'Export cashbook to file', true),
    ('finance.cashbook_legacy.read', 'Finance', 'cashbook_legacy', 'read', 'SCHOOL', 'View legacy cashbook endpoint (pre-unification)', true),
    ('finance.expense_ledger.read', 'Finance', 'expense_ledger', 'read', 'SCHOOL', 'View legacy activity-linked expense entries', true),
    ('finance.expense_ledger.create', 'Finance', 'expense_ledger', 'create', 'SCHOOL', 'Create legacy expense entry against an activity', true),
    ('finance.expense_ledger.approve', 'Finance', 'expense_ledger', 'approve', 'SCHOOL', 'Approve legacy expense entry', true),
    ('finance.expense_ledger.verify_payment', 'Finance', 'expense_ledger', 'verify_payment', 'SCHOOL', 'Verify payment on legacy expense entry', true),
    ('stock.register.read', 'Finance', 'register', 'read', 'SCHOOL', 'View consolidated stock register', true),
    ('stock.config.read', 'Finance', 'config', 'read', 'SCHOOL', 'View stock category configuration', true),
    ('stock.dashboard.read', 'Finance', 'dashboard', 'read', 'SCHOOL', 'View stock dashboard metrics', true),
    ('stock.entry.read', 'Finance', 'entry', 'read', 'SCHOOL', 'List and view stock entries', true),
    ('stock.entry.create', 'Finance', 'entry', 'create', 'SCHOOL', 'Record a stock purchase / inward entry', true),
    ('stock.issue.read', 'Finance', 'issue', 'read', 'SCHOOL', 'List stock issues', true),
    ('stock.issue.create', 'Finance', 'issue', 'create', 'SCHOOL', 'Issue stock to teacher, activity, or department', true),
    ('stock.audit_log.read', 'Finance', 'audit_log', 'read', 'SCHOOL', 'View stock change audit trail', true),
    ('user.read', 'System', 'user', 'read', 'SCHOOL', 'View user accounts in scope', true),
    ('user.register', 'System', 'user', 'register', 'SYSTEM', 'Create a user account (provision login)', true),
    ('user.teacher_link.read', 'System', 'teacher_link', 'read', 'SCHOOL', 'View user-teacher link', true),
    ('user.teacher_link.update', 'System', 'teacher_link', 'update', 'SCHOOL', 'Link or update user-teacher association', true),
    ('user.teacher_link.delete', 'System', 'teacher_link', 'delete', 'SCHOOL', 'Remove user-teacher link', true),
    ('system.school.read', 'System', 'school', 'read', 'SYSTEM', 'List schools in platform (tenant picker)', true),
    ('system.tenant.switch', 'System', 'tenant', 'switch', 'SYSTEM', 'Impersonate or switch school context with audit', true),
    ('system.permission_override.grant', 'System', 'permission_override', 'grant', 'SYSTEM', 'Grant temporary user permission override', true),
    ('system.permission_override.revoke', 'System', 'permission_override', 'revoke', 'SYSTEM', 'Revoke user permission override', true),
    ('pm_shri.dashboard.read', 'Finance', 'dashboard', 'read', 'SCHOOL', 'View PM SHRI programme dashboard', true),
    ('pm_shri.report.submit', 'Finance', 'report', 'submit', 'SCHOOL', 'Submit PM SHRI compliance report', true),
    ('pm_shri.activity.read', 'Finance', 'activity', 'read', 'SCHOOL', 'View PM SHRI-tagged activities', true),
    ('pm_shri.expense_request.create', 'Finance', 'expense_request', 'create', 'SELF', 'Create expense requests for PM SHRI activities', true),
    ('mdm.report.submit', 'Finance', 'report', 'submit', 'SCHOOL', 'Submit Mid-Day Meal compliance report', true),
    ('mdm.dashboard.read', 'Finance', 'dashboard', 'read', 'SCHOOL', 'View MDM operational dashboard', true),
    ('board_exam.result.create', 'Academics', 'result', 'create', 'SCHOOL', 'Enter or finalize board exam results school-wide', true),
    ('board_exam.result.read', 'Academics', 'result', 'read', 'SCHOOL', 'View board exam result compilation', true),
    ('board_exam.student.read', 'Academics', 'student', 'read', 'SCHOOL', 'View exam-candidate student lists', true),
    ('scholarship.student.read', 'Student', 'student', 'read', 'SCHOOL', 'View scholarship applicant records', true),
    ('scholarship.application.update', 'Student', 'application', 'update', 'SCHOOL', 'Update scholarship application status', true),
    ('scholarship.report.export', 'Student', 'report', 'export', 'SCHOOL', 'Export scholarship reports', true),
    ('sports.activity.create', 'Finance', 'activity', 'create', 'SCHOOL', 'Create sports activities and events', true),
    ('sports.activity.approve', 'Finance', 'activity', 'approve', 'SCHOOL', 'Approve sports activity budgets (within delegated limit)', true),
    ('sports.stock.issue', 'Finance', 'stock', 'issue', 'SCHOOL', 'Issue sports stock without principal co-sign', true),
    ('discipline.incident.create', 'Student', 'incident', 'create', 'SCHOOL', 'Record student discipline incident', true),
    ('discipline.incident.read', 'Student', 'incident', 'read', 'SCHOOL', 'View discipline register', true),
    ('discipline.incident.update', 'Student', 'incident', 'update', 'SCHOOL', 'Update discipline incident outcome', true),
    ('cultural.activity.create', 'Finance', 'activity', 'create', 'SCHOOL', 'Create cultural programmes and events', true),
    ('cultural.activity.read', 'Finance', 'activity', 'read', 'SCHOOL', 'View cultural activity portfolio', true),
    ('cultural.expense_request.create', 'Finance', 'expense_request', 'create', 'SELF', 'Raise expenses for cultural activities', true),
    ('ict.stock.read', 'Finance', 'stock', 'read', 'SCHOOL', 'View ICT stock and assets', true),
    ('ict.stock.issue', 'Finance', 'stock', 'issue', 'SCHOOL', 'Issue ICT equipment from stock register', true),
    ('ict.activity.create', 'Finance', 'activity', 'create', 'SCHOOL', 'Create ICT-related activities', true),
    ('udise.data.read', 'System', 'data', 'read', 'SCHOOL', 'View UDISE+ export datasets', true),
    ('udise.data.export', 'System', 'data', 'export', 'SCHOOL', 'Export UDISE+ submission files', true),
    ('udise.student.read', 'Student', 'student', 'read', 'SCHOOL', 'View student data quality reports for UDISE', true)
ON CONFLICT (permission_key) DO NOTHING;

-- =============================================================================
-- ROLLBACK (manual — delete seeded rows if reverting; does not drop schema)
-- =============================================================================
-- DELETE FROM permissions
-- WHERE permission_key IN (
--     SELECT unnest(ARRAY[
--         'dashboard.summary.read',
--         ... all 167 keys ...
--     ]::text[])
-- );
